version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER:     ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ~/data/mysql:/var/lib/mysql:delegated
    restart: unless-stopped
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    links:
      - php
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled/

      - ./logs/error.log:/var/log/nginx/error.log
      - ./logs/access.log:/var/log/nginx/access.log
      - ./logs/php.log:/var/log/nginx/php.log
      - ${VOLUME}:/var/www/vhosts
  php:
    build:
      context: ./php
    ports:
      - 9000:9000
    volumes:
      - ${VOLUME}:/var/www/vhosts
    environment:
          XDEBUG_CONFIG: remote_host=docker.for.mac.host.internal
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
