version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER:     ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql:delegated
    restart: unless-stopped
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    links:
      - php
    volumes:
      - ./nginx/default:/etc/nginx/sites-available/default
      - ./nginx/default:/etc/nginx/sites-enabled/default

      - ./logs/error.log:/var/log/nginx/error.log
      - ./logs/access.log:/var/log/nginx/access.log
      - ${VOLUME}:/var/www/vhosts
  php:
    image: php:fpm
    build:
      context: ./php
    ports:
      - 9000:9000
    volumes:
      - ${VOLUME}:/var/www/vhosts
volumes:
  mysql_data: 
    driver: local
    driver_opts:
      mountpoint: ~/data/mysql
